# Generated by Django 3.1.6 on 2021-02-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_profile', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TnpmTrapLookupRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя правила')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('is_enabled', models.BooleanField(default=False, help_text='Включение/Выключение , для записи в lookup', verbose_name='Включить')),
                ('metric_name', models.CharField(default=False, help_text='Опционально, будут отброшены только трапы указанной метрики', max_length=200, null=True, verbose_name='Имя метрики')),
                ('lookup_type', models.CharField(choices=[('discard', 'Отброс трапов по выбранным ресурсам'), ('low_traffic', 'Обогащение/отброс трапов по условию "низкого трафика"'), ('enrich_profile', 'Обогащение трапов данными о профиле')], default=('discard', 'Отброс трапов по выбранным ресурсам'), help_text='Отброс трапов по выбранным ресурсам:\n   Будут отброшены трапы от ресурсов, удовлетворябщих условиям фильтров\n\nОбогащение/отброс трапов по условию "низкого трафика":\n   Выгрузка данных будет сформирована на основании таблицы VM_INTFWTRAFFIC. Механизм сработает только для трапов, ID метрики которых содержится в выгрузке. В событие будет добавлено значение среднесуточного трафика, IN/OUT в зависимости от ID метрики. Если искомой комбинация ID ресурса + ID метрики нет в выгрузке, трап будет отброшен.\n\nОбогащение трапов данными о профиле:\n   В событие будет добавлено имя профиля, к которому относится ресурс', max_length=50, verbose_name='Имя свойства')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnpm.profilehelper', verbose_name='Выбор профиля')),
            ],
        ),
        migrations.CreateModel(
            name='TnpmElementFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(blank=True, choices=[['ifSpeed', 'ifSpeed'], ['ifDescr', 'ifDescr'], ['sysName', 'sysName']], default='ifSpeed', max_length=50, null=True, verbose_name='Имя свойства')),
                ('prop_compare', models.CharField(blank=True, choices=[(None, 'Ignore'), ('=.', '='), ('!=', '!='), ('LIKE.__icontains', 'LIKE'), ('NOT LIKE', 'NOT LIKE'), ('>.__gt', '>'), ('<.__lt', '<')], default=None, max_length=50, null=True, verbose_name='Условие сранения')),
                ('prop_value', models.CharField(blank=True, help_text='Значения поля', max_length=255, null=True, verbose_name='Значение')),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnpm.tnpmtraplookuprules')),
            ],
        ),
    ]
