# Generated by Django 3.1.6 on 2021-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0002_profilehelper_tnpmelementfilter_tnpmtraplookuprules'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tnpmelementfilter',
            name='prop_name',
        ),
        migrations.AlterField(
            model_name='tnpmelementfilter',
            name='prop_compare',
            field=models.CharField(blank=True, choices=[(None, 'Ignore'), ('=.', '='), ('!=.', '!='), ('LIKE.__icontains', 'LIKE'), ('NOT LIKE.', 'NOT LIKE'), ('>.__gt', '>'), ('<.__lt', '<')], default=None, max_length=50, null=True, verbose_name='Условие сранения'),
        ),
    ]
