# Generated by Django 3.1.6 on 2021-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0003_auto_20210215_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnpmelementfilter',
            name='prop_name',
            field=models.CharField(blank=True, choices=[['ifSpeed', 'ifSpeed'], ['ifDescr', 'ifDescr'], ['sysName', 'sysName']], default='ifSpeed', max_length=50, null=True, verbose_name='Имя свойства'),
        ),
    ]
