# Generated by Django 3.1.6 on 2021-02-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0004_tnpmelementfilter_prop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnpmelementfilter',
            name='selected_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tnpm.formulahelper', verbose_name='Поле автозаполнения'),
            preserve_default=False,
        ),
    ]
