# Generated by Django 3.1.6 on 2021-02-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0005_tnpmelementfilter_selected_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnpmelementfilter',
            name='prop_name',
        ),
    ]
