# Generated by Django 3.1.6 on 2021-02-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnpm', '0006_remove_tnpmelementfilter_prop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropDesc',
        ),
        migrations.RenameField(
            model_name='tnpmelementfilter',
            old_name='selected_name',
            new_name='prop_name',
        ),
    ]
